from fastapi import APIRouter, Request, Form, BackgroundTasks
from fastapi.templating import Jinja2Templates
from fastapi.responses import HTMLResponse, RedirectResponse
from typing import Optional, List
from pydantic import BaseModel
import os
import re
import httpx
import traceback
from psycopg2.extras import RealDictCursor
from langchain_openai import ChatOpenAI

from database import get_db_connection

router = APIRouter()
templates = Jinja2Templates(directory="templates")

class QAPair(BaseModel):
    question: str
    answer: str

class InterviewPayload(BaseModel):
    name: str
    email: str
    role: str
    phone: str
    education: str
    qa_pairs: List[QAPair]

def load_questions(role: str = None):
    # Auto-migrate database to add time_limit column if it doesn't exist
    try:
        conn = get_db_connection()
        cur = conn.cursor()
        cur.execute("ALTER TABLE questions ADD COLUMN IF NOT EXISTS time_limit INT DEFAULT 60;")
        conn.commit()
        cur.close()
        conn.close()
    except Exception as e:
        print("DB Migration Error (time_limit):", e)

    questions = []
    try:
        conn = get_db_connection()
        cur = conn.cursor(cursor_factory=RealDictCursor)
        if role:
            cur.execute("SELECT question_text, time_limit FROM questions WHERE role = %s ORDER BY id ASC", (role,))
        else:
            cur.execute("SELECT question_text, time_limit FROM questions ORDER BY id ASC")
        questions = [{'text': row['question_text'], 'time_limit': row.get('time_limit', 60)} for row in cur.fetchall()]
        cur.close()
        conn.close()
    except Exception as e:
        print("DB Load Questions Error:", e)
    return questions

def save_questions(role: str, questions: list, time_limits: list):
    try:
        conn = get_db_connection()
        cur = conn.cursor()
        cur.execute("DELETE FROM questions WHERE role = %s", (role,))
        for q, t in zip(questions, time_limits):
            cur.execute("INSERT INTO questions (role, question_text, time_limit) VALUES (%s, %s, %s)", (role, q, t))
        conn.commit()
        cur.close()
        conn.close()
    except Exception as e:
        print("DB Save Questions Error:", e)

def run_interview_analysis_task(name: str, email: str, role: str, phone: str, education: str, qa_pairs: List[QAPair]):
    job_description = "Job description not found."
    try:
        conn = get_db_connection()
        cur = conn.cursor()
        cur.execute("SELECT job_description FROM job_offers WHERE title_offer ILIKE %s LIMIT 1", (f"%{role}%",))
        res = cur.fetchone()
        if res:
            job_description = res[0]
        cur.close()
        conn.close()
    except Exception as e:
        print(f"Warning: Could not read job description from DB. Error: {e}")

    transcript_text = ""
    for idx, qa in enumerate(qa_pairs):
        transcript_text += f"Q{idx+1}: {qa.question}\nA{idx+1}: {qa.answer}\n\n"

    api_key = os.getenv("OPENROUTER_API_KEY")
    if not api_key:
        return

    # Phase 1: Refine and Correct the Transcript
    refine_prompt = f"""You are an expert Indonesian transcriber.
The following is an interview transcript generated by a Speech-to-Text engine. It may contain typos, misspellings, or phonetic mistakes.
Please read the transcript and correct any obvious spelling/grammar mistakes to make the candidate's answers clear and readable.
Do not change the actual meaning of their answers, just fix the typos.

Original Transcript:
{transcript_text}

Return ONLY the fully corrected transcript in the exact same Q&A format. Do not include any introductory or concluding text.
"""
    try:
        http_client = httpx.Client(verify=False)
        llm = ChatOpenAI(
            model="z-ai/glm-4.6",
            temperature=0.1,
            base_url="https://openrouter.ai/api/v1",
            api_key=api_key,
            http_client=http_client,
        )
        refined_response = llm.invoke(refine_prompt)
        refined_transcript = refined_response.content.strip()
    except Exception as e:
        print("Transcript Refinement Error:", e)
        refined_transcript = transcript_text # Fallback to original if refinement fails

    # Phase 2: Analyze and Score the Refined Transcript
    prompt = f"""You are an expert HR Interviewer. Please analyze the following candidate's interview transcript based on the requested Job Role.

Candidate Details:
- Name: {name}
- Applied Job Role: {role}

Job Description for {role}:
{job_description}

Interview Transcript:
{refined_transcript}

Task:
1. Evaluate the candidate's answers based strictly on how well their responses match the Job Description provided.
2. Provide an overall score for the interview out of 100.
3. Provide a detailed analysis of their strengths, weaknesses, and overall communication skills based on the transcript.
4. Please make it in points

Format your response EXACTLY as follows:
Score: [Your Score]
Analysis: [Your detailed analysis]

Don't use any '*' symbol on output. Please strictly use Indonesian language.
"""

    api_key = os.getenv("OPENROUTER_API_KEY")
    if not api_key:
        return

    try:
        http_client = httpx.Client(verify=False)
        llm = ChatOpenAI(
            model="z-ai/glm-4.6",
            temperature=0.3,
            base_url="https://openrouter.ai/api/v1",
            api_key=api_key,
            http_client=http_client,
        )
        try:
            response = llm.invoke(prompt)
            ai_output = response.content
        except Exception as api_err:
            print("OpenRouter API Error:", api_err)
            ai_output = "Score: N/A\nAnalysis: Terjadi kesalahan saat memproses wawancara dengan AI. Harap pastikan API Key sudah benar."


        score = "N/A"
        analysis_text = ai_output

        score_match = re.search(r"(?:Score|Skor):\s*(\d+)", ai_output, re.IGNORECASE)
        if score_match:
            score = score_match.group(1)

        analysis_match = re.split(r"(?:Analysis|Analisis):\s*", ai_output, maxsplit=1, flags=re.IGNORECASE)
        if len(analysis_match) > 1:
            analysis_text = analysis_match[1].strip()
        else:
            analysis_text = re.sub(r"(?:Score|Skor):\s*\d+\n?", "", ai_output, flags=re.IGNORECASE).strip()

        # Convert markdown **bold** to HTML strong tags
        analysis_text = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', analysis_text)
        # Convert markdown bullet points (*) to standard bullet characters (•)
        analysis_text = re.sub(r'(?m)^\s*\*\s+', r'• ', analysis_text)

        conn = get_db_connection()
        cur = conn.cursor()
        cur.execute("""
            INSERT INTO candidate_score (name, email, phone, education, role, score, score_type, resume_text, analysis)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
        """, (
            name,
            email,
            phone,
            education,
            role,
            int(score) if score.isdigit() else None,
            "Interview Score",
            refined_transcript[:30000],
            analysis_text
        ))
        conn.commit()
        cur.close()
        conn.close()

    except Exception as e:
        print(f"Background Task Error: {e}")


@router.get("/hr-setup", response_class=HTMLResponse)
async def hr_setup_page(request: Request, role: Optional[str] = None):
    roles = ["AI Engineer"]
    try:
        conn = get_db_connection()
        cur = conn.cursor(cursor_factory=RealDictCursor)
        cur.execute("SELECT DISTINCT title_offer FROM job_offers")
        db_roles = [row['title_offer'] for row in cur.fetchall()]
        if db_roles:
            roles = db_roles
        cur.close()
        conn.close()
    except Exception as e:
        pass

    selected_role = role if role else roles[0]
    questions = load_questions(selected_role)

    return templates.TemplateResponse(request=request, name="hr_setup.html", context={
        "request": request,
        "questions": questions,
        "roles": roles,
        "selected_role": selected_role
    })

@router.post("/save-questions", response_class=HTMLResponse)
async def save_questions_endpoint(request: Request, role: str = Form(...)):
    form_data = await request.form()
    questions_raw = form_data.getlist("questions")
    time_limits_raw = form_data.getlist("time_limits")

    questions = []
    time_limits = []
    for q, t in zip(questions_raw, time_limits_raw):
        if q.strip():
            questions.append(q.strip())
            time_limits.append(int(t) if t.isdigit() else 60)

    if role:
        save_questions(role, questions, time_limits)

    roles = [role]
    try:
        conn = get_db_connection()
        cur = conn.cursor(cursor_factory=RealDictCursor)
        cur.execute("SELECT DISTINCT title_offer FROM job_offers")
        db_roles = [row['title_offer'] for row in cur.fetchall()]
        if db_roles:
            roles = db_roles
        cur.close()
        conn.close()
    except Exception as e:
        pass

    return templates.TemplateResponse(request=request, name="hr_setup.html", context={
        "request": request,
        "questions": questions,
        "roles": roles,
        "selected_role": role,
        "message": f"Questions for {role} saved successfully!"
    })

@router.get("/interview", response_class=HTMLResponse)
async def interview_page(request: Request):
    user_email = request.cookies.get("user_email")
    if not user_email:
        return RedirectResponse(url="/", status_code=303)

    user_email = user_email.lower().strip()
    candidate_name = "Candidate"
    candidate_role = "AI Engineer"

    candidate_phone = ""
    candidate_education = ""
    try:
        conn = get_db_connection()
        cur = conn.cursor(cursor_factory=RealDictCursor)
        # Fetch the latest CV submission record to get the candidate's details
        cur.execute("SELECT name, role, phone, education FROM candidate_score WHERE email = %s AND score_type = 'CV Score' ORDER BY created_at DESC LIMIT 1", (user_email,))
        record = cur.fetchone()
        if record:
            candidate_name = record['name']
            candidate_role = record['role']
            candidate_phone = record['phone']
            candidate_education = record['education']
        cur.close()
        conn.close()
    except Exception as e:
        print("DB Fetch Candidate Error:", e)

    questions = load_questions(candidate_role)

    return templates.TemplateResponse(request=request, name="interview.html", context={
        "request": request,
        "questions": questions,
        "candidate_name": candidate_name,
        "candidate_email": user_email,
        "candidate_role": candidate_role,
        "candidate_phone": candidate_phone,
        "candidate_education": candidate_education
    })

@router.post("/analyze-interview")
async def analyze_interview(payload: InterviewPayload, background_tasks: BackgroundTasks):
    """
    Receive interview transcript, start background LLM task, and immediately respond.
    """
    # Push the heavily-processing task to run in the background
    background_tasks.add_task(run_interview_analysis_task, payload.name, payload.email, payload.role, payload.phone, payload.education, payload.qa_pairs)

    # Return success immediately to front end
    return {
        "success": True,
        "message": f"Terima kasih {payload.name} sudah mengikuti wawancara di Snappy!"
    }
